name: starter_template
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  animate_do: null
  cached_network_image: ^3.2.3
  collection: ^1.17.2
  copy_with_extension: ^5.0.2
  cupertino_icons: ^1.0.2
  curl_logger_dio_interceptor: ^1.0.0
  dartz: null
  dio: ^5.3.4
  dio_smart_retry: ^6.0.0
  equatable: ^2.0.5
  eva_icons_flutter: ^3.1.0
  flutter:
    sdk: flutter
  flutter_bloc: null
  flutter_dotenv: null
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_screenutil: ^5.9.0
  flutter_secure_storage: ^9.0.0
  freezed_annotation: ^2.4.1
  get_it: ^7.7.0
  get_storage: ^2.1.1
  go_router: ^12.1.1
  google_fonts: ^6.1.0
  injectable: ^2.3.2
  internet_connection_checker: ^1.0.0+1
  intl: any
  json_annotation: ^4.8.0
  logger: ^2.0.2+1
  lottie: ^2.7.0
  package_info_plus: ^5.0.1
  permission_handler: ^11.1.0
  pretty_animated_buttons: null
  pretty_dio_logger: null
  riverpod: ^2.5.1
  shared_preferences: ^2.2.2

dev_dependencies:
  analyzer: null
  build_runner: ^2.4.7
  copy_with_extension_gen: ^5.0.4
  dart_code_metrics_presets: ^2.6.0

  flutter_launcher_icons: ^0.13.0

  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1

  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1

flutter:
  # generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/
    - assets/fonts/
    - assets/json/
